"""add_cascade_delete_to_claims

Revision ID: 3cfcf4d3cd8d
Revises: f1ad673a2090
Create Date: 2024-11-26 17:23:27.425653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfcf4d3cd8d'
down_revision: Union[str, None] = 'f1ad673a2090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('claims_member_id_fkey', 'claims', type_='foreignkey')
    op.create_foreign_key(None, 'claims', 'members', ['member_id'], ['database_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.create_foreign_key('claims_member_id_fkey', 'claims', 'members', ['member_id'], ['database_id'])
    # ### end Alembic commands ###
