"""create_claims_table

Revision ID: 9f371a4befb2
Revises: a21aa60c26eb
Create Date: 2024-11-25 19:06:49.634455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f371a4befb2'
down_revision: Union[str, None] = 'a21aa60c26eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('claim_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('service_provider_id_qualifier', sa.CHAR(length=2), nullable=False),
    sa.Column('service_provider_id', sa.VARCHAR(length=15), nullable=False),
    sa.Column('other_payer_id_qualifier', sa.CHAR(length=2), nullable=True),
    sa.Column('other_payer_id', sa.VARCHAR(length=15), nullable=True),
    sa.Column('other_payer_amount_paid', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('diagnosis_code_qualifier', sa.CHAR(length=2), nullable=True),
    sa.Column('diagnosis_code', sa.VARCHAR(length=15), nullable=True),
    sa.Column('clinical_information', sa.TEXT(), nullable=True),
    sa.Column('prescription_service_reference_number_qualifier', sa.TEXT(), nullable=True),
    sa.Column('prescription_service_reference_number', sa.TEXT(), nullable=True),
    sa.Column('product_service_id_qualifier', sa.TEXT(), nullable=True),
    sa.Column('product_service_id', sa.TEXT(), nullable=True),
    sa.Column('quantity_dispensed', sa.Integer(), nullable=True),
    sa.Column('fill_number', sa.Integer(), nullable=True),
    sa.Column('ndc_number', sa.TEXT(), nullable=True),
    sa.Column('days_supply', sa.Integer(), nullable=True),
    sa.Column('dispense_as_written', sa.Boolean(), nullable=True),
    sa.Column('date_prescription_written', sa.Date(), nullable=True),
    sa.Column('prescription_origin_code', sa.TEXT(), nullable=True),
    sa.Column('other_coverage_code', sa.TEXT(), nullable=True),
    sa.Column('special_packaging_indicator', sa.Boolean(), nullable=True),
    sa.Column('unit_of_measure', sa.TEXT(), nullable=True),
    sa.Column('ingredient_cost_submitted', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('dispensing_fee_submitted', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('patient_paid_amount_submitted', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('usual_and_customary_charge', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('gross_amount_due', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('basis_of_cost_determination', sa.TEXT(), nullable=True),
    sa.Column('prescriber_id_qualifier', sa.TEXT(), nullable=True),
    sa.Column('prescriber_id', sa.TEXT(), nullable=True),
    sa.Column('prescriber_last_name', sa.TEXT(), nullable=True),
    sa.Column('prescriber_phone_number', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.database_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claims')
    # ### end Alembic commands ###
