"""create_members_table

Revision ID: a21aa60c26eb
Revises: 
Create Date: 2024-11-25 16:39:25.640730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21aa60c26eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('database_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.TEXT(), nullable=True),
    sa.Column('first_name', sa.TEXT(), nullable=True),
    sa.Column('last_name', sa.TEXT(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.CHAR(length=1), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('state', sa.TEXT(), nullable=True),
    sa.Column('zip_code', sa.TEXT(), nullable=True),
    sa.Column('phone_number', sa.TEXT(), nullable=True),
    sa.Column('insurance_id_number', sa.TEXT(), nullable=True),
    sa.Column('group_number', sa.TEXT(), nullable=True),
    sa.Column('rx_bin', sa.TEXT(), nullable=True),
    sa.Column('rx_group', sa.TEXT(), nullable=True),
    sa.Column('rx_pcn', sa.TEXT(), nullable=True),
    sa.Column('copay_1_generic', sa.TEXT(), nullable=True),
    sa.Column('copay_2_preferred', sa.TEXT(), nullable=True),
    sa.Column('copay_3_non_preferred', sa.TEXT(), nullable=True),
    sa.Column('copay_4_specialty', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('database_id'),
    sa.UniqueConstraint('member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
